### ISSUE TITLE
ICMP Tunnel?

### ISSUE THREAD

**Issue by tin7safe** [knownsec/Portforward#1]
要不要考虑支持下ICMP的通道。

**Comment by 0x7Fancy** [comment]
不考虑支持，端口转发(以及代理)工作在传输层，ICMP 工作在网络层。可以尝试使用 vpn 的方案来解决这类问题

**Comment by 0x7Fancy** [comment]
可能之前理解的不对，如果你说的是 ICMP 隧道的话，也是不考虑支持的；目前端口转发只是原始流量转发，加上隧道的话，应该是代理的功能了，有部分代理软件支持 ICMP 隧道
